pipeline{
  agent any
  tools {
    nodejs 'node-11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependecies') {
      steps {
        sh 'cd jenkins-test && npm i'
      }
    }

    stage('Run tests') {
      steps {
        sh 'cd jenkins-test && npm t'
      }
    }
  }
}
